<template>
  <div class="container">
    <div class="filter"></div>
    <div class="list-book">
      <BookItem
        class="book-item"
        v-for="book in books"
        :key="book.id"
        :id="book.id"
        :name="book.name"
        :img="book.img"
        :price="book.price"
        :rate="book.rate"
      />
    </div>
  </div>
</template>

<script>
import { ref } from "vue";
import BookItem from "@/components/widgets/index/displayBooks/BookSliderItem.vue";
export default {
  components: {
    BookItem,
  },
  setup() {
    const books = ref([
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 0,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 1,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 2,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 3,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 4,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 5,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 6,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 7,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 8,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 9,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 10,
        img: "book1.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 11,
        img: "book2.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 12,
        img: "book3.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 13,
        img: "book4.jpg",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 14,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 15,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 16,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 17,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 18,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 19,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
      {
        id: 20,
        img: "book5.webp",
        name: "Khách sạn mặt nạ",
        price: "$10.00",
        rate: 4,
      },
    ]);

    return {
      books,
    };
  },
};
</script>

<style scoped>
.container {
  display: flex;
  margin: 2rem auto;
  max-width: 90%;
}

.filter {
  width: 20rem;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.22);
  height: 85vh;
  position: sticky;
  top: 7rem;
  border-radius: 0.2rem;
}

.list-book {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(15rem, 1fr));
  gap: 1rem;
  max-width: 80%;
  margin-left: 2rem;
}

@media (max-width: 700px) {
  .list-book {
    grid-template-columns: repeat(auto-fit, minmax(15rem, 1fr));
    margin: auto;
  }

  .filter {
    display: none;
  }
}
</style>
